### ISSUE TITLE
Keyname conventions: mismatch between description and actual appearance

### ISSUE THREAD

**Issue by SpotlightKid** [prokoudine/ardour-tutorial#14]
https://prokoudine.github.io/ardour-tutorial/en/introduction/conventions/ states:

> The names of keys to be pressed are written in quotation marks and italicised

But in the browser (checked in FF and Chromium) the example shown neither is italicised nor does it have quotation marks:

![grafik](https://github.com/prokoudine/ardour-tutorial/assets/5719151/01374d4b-dbc9-46dd-a076-2dec5122874e)

**Comment by prokoudine** [comment]
Thanks, fixed!

**Comment by jujudusud** [comment]
Needs to be translated.
I will add that to my todo list. ;-)
