### ISSUE TITLE
Some images are not shown in french pages.

### ISSUE THREAD

**Issue by jujudusud** [prokoudine/ardour-tutorial#21]
I have a "bug" or something else with showing the english screenshot in the french pages.

It is working perfectly here: [recorder window](https://prokoudine.github.io/ardour-tutorial/fr/getting-started/overview-of-the-interface/recorder-window/)
but not here, for exemple: [overview of the interface](https://prokoudine.github.io/ardour-tutorial/fr/getting-started/overview-of-the-interface/)

I need some help to solve this issue.

**Comment by prokoudine** [comment]
Beats me! For some reason localized version doens't load the same image with the same path.

@patdavid, any idea of Hugo is known to play silly buggers here?

**Comment by jujudusud** [comment]
Any news here?
Do we have to add french screenshots?

**Comment by prokoudine** [comment]
No news, I've been unable to figure it out.

**Comment by jujudusud** [comment]
I will test adding screenshots in a fr directory.
As soon as possible.

**Comment by jujudusud** [comment]
I noticed something. I don't know how it works but :
- in the /en/ root folder it has another /en/ folder in "overview of the interface" with the English screenshots.
- there is also a /fr/ folder that should be located in /fr/ instead of /en/
![Capture d’écran_2024-02-14_23-57-00](https://github.com/prokoudine/ardour-tutorial/assets/12748768/2282c257-1055-4f28-a38d-a7a093e16f11)
- this folder should be called /en/ in the /en/ root folder and /fr/ in the /fr/ root folder
- But it is not present -> error 404
![Capture d’écran_2024-02-14_23-56-18](https://github.com/prokoudine/ardour-tutorial/assets/12748768/adcbfb03-54f1-45b6-914b-c60129256a8f)

**Comment by jujudusud** [comment]
ok, understood!
we have to add .fr to the img names ... :-) as in index.fr.md
in fr folder, Ardour6_Clocks.png will become Ardour6_Clocks.fr.png
It seems to be as easy as that.

**Comment by patdavid** [comment]
You don't _need_ an `en/` or `fr/` folder I think for images.

If you have a file `index.fr.md` - you can reference a local image in your file like `![](some-local-image.jpg)` if `some-local-image.jpg` exists alongside the markdown file.  Then you can reference the same file in any language file.

```
├── fancy-page-name
│   ├── my-image.jpg
│   ├── index.en.md
│   └── index.fr.md

```
With the above, you can reference `my-image.jpg` from any `index.LANG.md` file (ie: `![](my-image.jpg)`).
If you really do have another language version of an image you _can_ just add the lang code to it if you want (or any other name, really).

**Comment by jujudusud** [comment]
Thanks @patdavid for the help here.
@prokoudine , we now need to "align" the names of the images file names in the links by adding also ".fr".

**Comment by jujudusud** [comment]
Cross fingers.
Will be ok with #24 merged

**Comment by jujudusud** [comment]
Everything is working now.
Closing here.
