### ISSUE TITLE
Typos in the english version

### ISSUE THREAD

**Issue by grock** [prokoudine/ardour-tutorial#25]
Hi, while reading the english version of the tutorial, I noted about 50 typos and small text mistakes over the length of the whole tutorial. I would be willing to correct them myself and submit a pull request, I'm just asking if you are interested in such contribution before starting?

Thanks.

**Comment by prokoudine** [comment]
Yes, absolutely. Thank you :)

**Comment by grock** [comment]
Here is a list of some other typos that I wasn't sure how to fix:

**Editing session > Working with regions** (Chapter 4)
In the "Splitting Regions" section, in the second bullet point, the "Edit > Split Region" seems to now be called "Edit > Split/Separate".

**Editing sessions > Changing edit modes** (Chapter 4)
"Audition Mode" doesn't seem to exist anymore, and "Grid Mode" seems to have been added too.

**Editing sessions > Changing edit modes** (Chapter 4)
In the "Stretch/Shrink Region" section, the image doesn't load.

**Editing sessions > Editing MIDI regions** (Chapter 4)
In the "Editing example start to end" section, at number 8, the second sentence is missing a word or two, or a word is misspelled, "You will now how a regular...". (maybe "how" should be replaced by "have"?)

**Mixing sessions > Using automation** (Chapter 5)
In the "Automation States" section, the description of the "Latch" value is missing.

**Glossary**
Edit Modes : "Slice Edit" doesn't seem to appear, but "Ripple" is there instead.
MIDI : "^" characters reference an hyperlink in the page's code, but no link is shown.
Pitch : Same as MIDI.
Reverberation : Same as MIDI.

**Comment by prokoudine** [comment]
Thanks a lot! I think I fixed all of the above. If not, please reopen :)
