### ISSUE TITLE
english version showing russian submenu

### ISSUE THREAD

**Issue by jmahler** [prokoudine/ardour-tutorial#29]
For some reason the english version of the page is showing a russian menu (see screenshot).
I noticed this with the Recording menu and several others.

![Screenshot from 2024-12-20 17-37-36](https://github.com/user-attachments/assets/ebb80ad0-ec7c-4e80-b3b4-75dcbb698788)

**Comment by prokoudine** [comment]
Thanks, I'll have a look at that

**Comment by prokoudine** [comment]
OK, I fixed that in a somewhat harsh way but it works now :)
