### ISSUE TITLE
Maybe this should be linked to from ardour.org?

### ISSUE THREAD

**Issue by agraef** [prokoudine/ardour-tutorial#9]
@prokoudine, while replying to https://github.com/Ardour/ardour/pull/808#issuecomment-1637955008, I noticed that you maintain this updated version of Bruno's (et al) Ardour tutorial. That's awesome, I'll point my students to it. I wasn't even aware that such an updated version exists. Maybe this should be linked to somewhere on ardour.org, instead of the rather outdated FLOSS manual? Or is there a reason that this isn't already the case?

At least, you could add https://prokoudine.github.io/ardour-tutorial/en/ as a website link to the repo (and, while you're at it, also to the README), that would make the deployed version easier to find.

**Comment by prokoudine** [comment]
Ardour is already pointing to that version, e.g. if you use the Help menu in the program.

**Comment by agraef** [comment]
Ok, that's even better. :)
